steps:
  - label: ":pipeline: Run Trinity Desktop (PRs) pipeline"
    command:
      - "yarn"
      - "yarn deps:shared"
      - "yarn deps:desktop"
      - "cd src/desktop && yarn auditjs && cd ../.."
      - "yarn lint:desktop"
      - "cd src/desktop && npm run build"
    agents:
      queue: dev
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
        image: "iotacafe/trinity-desktop-ci:38ef883-8"
