steps:
  - name: Signing zeronet hosts
    command: ansible-playbook -i hosts.ini playbooks/ssh-host-sign.yml --limit zeronet
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
          - HOST_TOKEN
    agents:
      queue: aws-nano

  - wait: ~

  - name: Signing spamnet hosts
    command: ansible-playbook -i hosts.ini playbooks/ssh-host-sign.yml --limit spamnet
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
          - HOST_TOKEN
    agents:
      queue: aws-nano

#  - block: "Push to devnet"
  - wait: ~

  - name: Signing devnet hosts
    command: ansible-playbook -i hosts.ini playbooks/ssh-host-sign.yml --limit devnet
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
          - HOST_TOKEN
    agents:
      queue: aws-nano

#  - block: "Push to mainnet"
  - wait: ~
  
  - name: Signing mainnet hosts
    command: ansible-playbook -i hosts.ini playbooks/ssh-host-sign.yml --limit mainnet
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
          - HOST_TOKEN
    agents:
      queue: aws-nano